name: Publish Node package
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"
      - run: npm i -g pnpm@8.6.10
      - run: pnpm i
        working-directory: ./node
      - run: pnpm publish --access public
        working-directory: ./node
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
